<template>
     <section id="contact" class="min-h-screen">
        <div>Experience</div>
        <div>
            <ul class="list-disc">
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
                <li>sdjkhjksd</li>
        </ul>
    </div>
     </section>
</template>